### PR TITLE
Added Releases page

### PR DESCRIPTION
**Pull request by Yaya-Cout**
I added a release page with a change log. If you want, you can change the style of the page (I copied the style of the LaTeX doc and of Omega)

### CODE REVIEW

**Comment by lolocomotive** [comment]
It would be nice if there was a plus next to some features to expand them and get more information about the feature (for example for the python modules)
Either expand or link to a documentation page (you could do a python doc page with all the different modules and link to a specific part of the page instead of one documentation page per module) idk

**Comment by lolocomotive** [comment]
The tags are a bit flashy (especially the red ones) so maybe change the colors a bit, also maybe add a fix tag. And also list them from the most important to the least important (So new before upd) and group changes of the same things together (All python related changes together, all settings together etc... (So you could maybe make categories but idk if it would actually be better or not))

**Comment by lolocomotive** [comment]
And as far as the naming conventions go, for classes I prefer to separate works with dashes, so `updatetagupdate` should become `update-tag-update`

**Comment by Yaya-Cout** [comment]
The name of the CSS tag, the order of release content and the tag color are fixed

**Pull request merged**
